apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nq6ql7gm5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nq6ql7gm5-java-quarkus-gitops